In [1]:
import pandas as pd

In [3]:
r = pd.read_csv('rides.csv', skipinitialspace=True)

In [5]:
r['Start Date']

0         2023-04-22 09:01:03
1         2023-04-22 09:01:07
2         2023-04-22 09:04:27
3         2023-04-22 09:06:34
4         2023-04-22 09:09:27
                 ...
102250    2023-07-31 23:45:06
102251    2023-07-31 23:46:01
102252    2023-07-31 23:48:04
102253    2023-07-31 23:51:41
102254    2023-07-31 23:57:01
Name: Start Date, Length: 102255, dtype: object

In [7]:
set(r['Start Date'].apply(lambda x: len(x)))

{19}

In [117]:
r['Start Date'] = r['Start Date'].apply(lambda x: pd.to_datetime(x))

In [118]:
r['Days'] = r['Start Date'].apply(lambda x: x.day)

In [119]:
r['Month'] = r['Start Date'].apply(lambda x: x.month)

In [120]:
def time_day(x):
    if 5 <= x <= 12:
        return 'Morning'
    elif 12 < x <= 18:
        return 'Day'
    elif 18 < x <= 22:
        return 'Evening'
    return 'Night'

In [95]:
r['time_of_day'] = r['Start Date'].apply(lambda x: time_day(x.hour))

In [96]:
r = r[r['End Date'] != 'NaT']

In [97]:
r['End Date'] = r['End Date'].apply(lambda x: pd.to_datetime(x))

In [98]:
r['Duration'] = r['End Date'] - r['Start Date']

In [99]:
r

,Id,Start Date,End Date,Start Location,Start District,End Location,End District,Distance,Promo,Days,Month,time_of_day,Duration
0,100340,2023-04-22 09:01:03,2023-04-22 09:24:45,Шевченко,Юго-Восточный,Майская,Октябрьский,4069.0,0,22,4,Morning,0 days 00:23:42
1,100341,2023-04-22 09:01:07,2023-04-22 09:29:32,Чехова,заречный,Спортивная,октябрьский,4515.0,0,22,4,Morning,0 days 00:28:25
2,100342,2023-04-22 09:04:27,2023-04-22 09:42:46,Буденного,Октябрьский,Суворова,ленинский,4520.0,0,22,4,Morning,0 days 00:38:19
3,100343,2023-04-22 09:06:34,2023-04-22 09:38:23,Труда,Центральный,Рабочая,Северо-Западный,3881.0,0,22,4,Morning,0 days 00:31:49
4,100344,2023-04-22 09:09:27,2023-04-22 09:40:07,Первомайская,Северо-Западный,Юбилейная,Юго-Восточный,4029.0,0,22,4,Morning,0 days 00:30:40
...,...,...,...,...,...,...,...,...,...,...,...,...,...
102250,197707,2023-07-31 23:45:06,2023-08-01 00:06:55,Озерная,Юго-Восточный,Первомайская,Северо-Западный,3302.0,0,31,7,Night,0 days 00:21:49
102251,197708,2023-07-31 23:46:01,2023-08-01 00:25:35,Мичурина,Ленинский,Садовая,Заречный,4992.0,0,31,7,Night,0 days 00:39:34
102252,197709,2023-07-31 23:48:04,2023-08-01 00:09:21,Лермонтова,ленинский,Куйбышева,Центральный,2781.0,0,31,7,Night,0 days 00:21:17
102253,197710,2023-07-31 23:51:41,2023-08-01 00:38:04,Рябиновая,Северо-Западный,Энергетиков,Юго-Восточный,6466.0,0,31,7,Night,0 days 00:46:23
102254,197711,2023-07-31 23:57:01,2023-08-01 00:19:03,Молодежная,Юго-Восточный,Маяковского,Центральный,3561.0,0,31,7,Night,0 days 00:22:02

In [ ]:
def formating(x):
    s = x.seconds
    hour = x.seconds // 3600
    minutes = (x.seconds - x.seconds // 3600) // 60
    sec = (x.seconds - x.seconds // 3600) % 60
    a = []
    for i in [hour, minutes, sec]:
        a.append(str(i))
    return a

r['Duration'] = r['Duration'].apply(lambda x: ' '.join(formating(x)))

In [ ]:
r['stupid_duration'] = r['End Date'] - r['Start Date']
r['stupid_duration'] = r['stupid_duration'].apply(lambda x: x.seconds)

In [ ]:
r = r.dropna()

In [ ]:
r['Average_speed'] = r['Distance'] / r['stupid_duration']

In [ ]:
r['Average_speed'] = r['Average_speed'].apply(lambda x: round(x * 3.6, 1))

In [ ]:
def time_of_the_year(x):
    d = {
        1: 'Winter',
        2: 'Winter',
        3: 'Spring',
        4: 'Spring',
        5: 'Spring',
        6: 'Summer',
        7: 'Summer',
        8: 'Summer',
        9: 'Autumn',
        10: 'Autumn',
        11: 'Autumn',
        12: 'Winter',
    }
    return d[x]

In [ ]:
r['Month'] = r['Month'].apply(time_of_the_year)

In [ ]:
dw = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

In [ ]:
r['Days'] = r['Start Date'].apply(lambda x: dw[x.day_of_week])

In [ ]:
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns

# plt.figure(figsize=(8, 6))
# sns.countplot(x='Days', data=r, palette='Set2')

# plt.title('Распределение категориальных признаков', fontsize=16)
# plt.xlabel('Категория', fontsize=12)
# plt.ylabel('Частота', fontsize=12)

# plt.show()

In [ ]:
r = r[r['Distance'] < 10000]
r = r[r['Distance'] > 10]

In [ ]:
# import pandas as pd
# import seaborn as sns
# import matplotlib.pyplot as plt
# import numpy as np
# from scipy.stats import pearsonr, spearmanr, chi2_contingency

# df = r.copy()

# # Функция для вычисления корреляции между столбцами
# def calc_correlation(col1, col2):
#     if col1.dtype == 'object' and col2.dtype == 'object':
#         contingency_table = pd.crosstab(col1, col2)
#         chi2, p, dof, ex = chi2_contingency(contingency_table)
#         cramer_v = np.sqrt(chi2 / (col1.shape[0] * (min(contingency_table.shape) - 1)))
#         return cramer_v
#     elif col1.dtype != 'object' and col2.dtype != 'object':  # Числовые-Числовые
#         corr, _ = pearsonr(col1, col2)
#         return corr
#     else:  # Числовые-Категориальные
#         # Применяем тест хи-квадрат или ранговую корреляцию
#         if col1.dtype != 'object':  # Числовой столбец в первом месте
#             corr, _ = spearmanr(col1, col2)
#         else:  # Числовой столбец во втором месте
#             corr, _ = spearmanr(col2, col1)
#         return corr

# # Создаем пустую матрицу для хранения корреляций
# columns = list(df.columns)
# columns.remove('Start Date')
# columns.remove('End Date')
# columns.remove('Id')
# columns.remove('Duration')
# correlation_matrix = pd.DataFrame(index=columns, columns=columns)

# # Заполняем матрицу корреляции
# for col1 in columns:
#     for col2 in columns:
#         correlation_matrix.loc[col1, col2] = calc_correlation(df[col1], df[col2])

# # Преобразуем все значения в числовой формат для дальнейшего отображения
# correlation_matrix = correlation_matrix.astype(float)

# # Строим тепловую карту для отображения матрицы корреляций
# plt.figure(figsize=(8, 6))
# sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
# plt.title('Матрица корреляций (числовые и категориальные данные)', fontsize=16)
# plt.show()

In [ ]:
# sns.set(style="whitegrid")
# plt.figure(figsize=(10, 6))
# sns.histplot(list(r['stupid_duration']), kde=True, bins=10, color='skyblue', stat='density')

# # Настроим подписи и заголовок
# plt.title('Распределение продолжительности поездок', fontsize=16)
# plt.xlabel('Продолжительность поездки (секунды)', fontsize=12)
# plt.ylabel('Плотность', fontsize=12)

# # Покажем график
# plt.show()

In [ ]:
w = pd.read_csv('weather.csv')

In [ ]:
w['Precipitation Total'] = w['Precipitation Total'].fillna(method='ffill')
w['Wind Speed'] = w['Wind Speed'].fillna(method='ffill')
w['Cloud Cover Total'] = w['Cloud Cover Total'].fillna(method='ffill')
w['Sunshine Duration'] = w['Sunshine Duration'].fillna(method='ffill')

In [ ]:
# plt.figure(figsize=(10, 6))
# plt.plot([i for i in range(len(w))], list(w.fillna(0)['Temperature'].astype('float')), marker='o', linestyle='-', color='b', label='Value')

# # Настройка графика
# plt.title('Изменения значения на протяжении времени', fontsize=16)
# plt.xlabel('Время', fontsize=12)
# plt.ylabel('Значение', fontsize=12)
# plt.xticks(rotation=45)  # Повернем метки времени для удобства
# plt.grid(True)
# plt.legend()

# # Покажем график
# plt.tight_layout()
# plt.show()

In [ ]:
w['Time of the year'] = w['Datetime'].apply(lambda x: time_of_the_year(pd.to_datetime(x).month))

In [ ]:
test_df = w[w['Temperature'].isna()]  # Строки, где Temperature == NaN
train_df = w[w['Temperature'].notna()]  # Строки, где Temperature не NaN

In [ ]:
len(test_df)

In [ ]:
# plt.figure(figsize=(10, 6))
# plt.plot([i for i in range(len(train_df))], list(train_df.fillna(7)['Precipitation Total'].astype('float')), marker='o', linestyle='-', color='b', label='Value')

# # Настройка графика
# plt.title('Изменения значения на протяжении времени', fontsize=16)
# plt.xlabel('Время', fontsize=12)
# plt.ylabel('Значение', fontsize=12)
# plt.xticks(rotation=45)  # Повернем метки времени для удобства
# plt.grid(True)
# plt.legend()

# # Покажем график
# plt.tight_layout()
# plt.show()

In [ ]:
train_df['Precipitation Total'] = train_df['Precipitation Total'].astype('float')
train_df = train_df[train_df['Precipitation Total'] < 3]

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [ ]:
df_ohe = pd.get_dummies(train_df, columns=['Time of the year'], prefix='Category')

In [ ]:
df_ohe['Category_Summer'] = df_ohe['Category_Summer'].astype('float')
df_ohe['Category_Spring'] = df_ohe['Category_Spring'].astype('float')

In [ ]:
df_ohe = df_ohe.drop(columns=['Datetime'])

In [ ]:
df_ohe.isna().sum()

In [ ]:
X = df_ohe[['Precipitation Total', 'Wind Gust', 'Wind Speed', 'Cloud Cover Total', 'Sunshine Duration', 'Category_Spring', 'Category_Summer']]  # Признаки (вектора)
y = df_ohe['Temperature']  # Целевой признак (то, что нужно предсказать)

# Разделяем на обучающую и тестовую выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Создаем модель линейной регрессии
model = LinearRegression()

# Обучаем модель
model.fit(X_train, y_train)

# Делаем предсказания на тестовых данных
y_pred = model.predict(X_test)

# Оценим качество модели (с помощью MSE - Среднеквадратичной ошибки)
mse = mean_squared_error(y_test, y_pred)

# Выводим результаты
print(f"Среднеквадратичная ошибка: {mse}")

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=2)  # Степень полинома
X_poly = poly.fit_transform(X)

# Разделяем данные на обучающие и тестовые
X_train_poly, X_test_poly, y_train, y_test = train_test_split(X_poly, y, test_size=0.2, random_state=42)

# Линейная регрессия для полиномиальных признаков
poly_model = LinearRegression()
poly_model.fit(X_train_poly, y_train)

# Прогнозирование
y_pred_poly = poly_model.predict(X_test_poly)

# Оценка модели
mse_poly = mean_squared_error(y_test, y_pred_poly)
print(f"Среднеквадратичная ошибка (MSE) для Polynomial Regression: {mse_poly}")

In [ ]:
from sklearn.svm import SVR

# Поддерживающая векторная машина (SVM)
svm_model = SVR(kernel='linear')  # Можно использовать различные ядра
svm_model.fit(X_train, y_train)

# Прогнозирование
y_pred_svm = svm_model.predict(X_test)

# Оценка модели
mse_svm = mean_squared_error(y_test, y_pred_svm)
print(f"Среднеквадратичная ошибка (MSE) для SVM: {mse_svm}")

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

# Градиентный бустинг
gb_model = GradientBoostingRegressor(n_estimators=100, random_state=42)
gb_model.fit(X_train, y_train)

# Прогнозирование
y_pred_gb = gb_model.predict(X_test)

# Оценка модели
mse_gb = mean_squared_error(y_test, y_pred_gb)
print(f"Среднеквадратичная ошибка (MSE) для Gradient Boosting: {mse_gb}")

In [ ]:
from catboost import CatBoostRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

model = CatBoostRegressor(iterations=10000,  # Максимальное количество итераций
                          learning_rate=0.1,  # Коэффициент обучения
                          depth=6,  # Глубина деревьев
                          cat_features=[],  # Список категориальных признаков (если есть)
                          verbose=200,  # Печать прогресса
                          early_stopping_rounds=50)  # Останавливаем обучение, если ошибка не улучшается в течение 50 раундов

# Обучение модели с валидацией на валидационном наборе
model.fit(X_train, y_train, eval_set=(X_test, y_test), use_best_model=True)

# Прогнозирование
y_pred = model.predict(X_test)

# Оценка модели
mse = mean_squared_error(y_test, y_pred)
print(f"Среднеквадратичная ошибка (MSE) на тестовых данных: {mse}")

In [ ]:
df_ohe1 = pd.get_dummies(test_df, columns=['Time of the year'], prefix='Category')
df_ohe1['Category_Summer'] = df_ohe1['Category_Summer'].astype('float')
df_ohe1['Category_Spring'] = df_ohe1['Category_Spring'].astype('float')
y_pred1 = model.predict(df_ohe1[['Precipitation Total', 'Wind Gust', 'Wind Speed', 'Cloud Cover Total', 'Sunshine Duration', 'Category_Spring', 'Category_Summer']])

In [ ]:
test_df['Temperature'] = y_pred1

In [ ]:
test_df

In [ ]:
# plt.figure(figsize=(10, 6))
# plt.plot([i for i in range(len(test_df))], list(test_df['Temperature'].astype('float')), marker='o', linestyle='-', color='b', label='Value')

# # Настройка графика
# plt.title('Изменения значения на протяжении времени', fontsize=16)
# plt.xlabel('Время', fontsize=12)
# plt.ylabel('Значение', fontsize=12)
# plt.xticks(rotation=45)  # Повернем метки времени для удобства
# plt.grid(True)
# plt.legend()

# # Покажем график
# plt.tight_layout()
# plt.show()

In [ ]:
test_df['Datetime'] = test_df['Datetime'].apply(lambda x: pd.to_datetime(x))
train_df['Datetime'] = train_df['Datetime'].apply(lambda x: pd.to_datetime(x))

In [ ]:
merged_df = pd.concat([train_df, test_df])  # Можно выбрать тип слияния: 'inner', 'outer', 'left', 'right'
w1 = merged_df.copy()

In [ ]:
sorted(set(w1['Datetime']))

In [ ]:
ti = w1['Datetime'].min()
lim = w1['Datetime'].max()
while ti != lim:
    ti += pd.Timedelta(1, "h")
    if ti not in w1['Datetime'].to_list():
        print(ti)

In [ ]:
from IPython.display import clear_output


def find_nearest_date(date1, df2):
    diff1 = abs(df2['Datetime'] - date1).idxmin()
    clear_output(wait=True)
    print(date1)
    return df2.loc[diff1]

# Создаем новый DataFrame для хранения результата
merged_rows = []

# Для каждой строки в df1 находим ближайшую дату в df2
for _, row in r.iterrows():
    nearest_row = find_nearest_date(row['Start Date'], w1)
    # Объединяем строки по найденной ближайшей дате
    merged_row = pd.concat([row, nearest_row], axis=0)
    merged_rows.append(merged_row)

# Преобразуем список строк в DataFrame
merged_df = pd.DataFrame(merged_rows)
merged_df

In [121]:
merged_df = merged_df.reset_index(drop=True)

NameError: name 'merged_df' is not defined

In [ ]:
merged_df

In [ ]:
# import pandas as pd
# import seaborn as sns
# import matplotlib.pyplot as plt
# import numpy as np
# from scipy.stats import pearsonr, spearmanr, chi2_contingency

# df = merged_df.copy()

# # Функция для вычисления корреляции между столбцами
# def calc_correlation(col1, col2):
#     if col1.dtype == 'object' and col2.dtype == 'object':
#         contingency_table = pd.crosstab(col1, col2)
#         chi2, p, dof, ex = chi2_contingency(contingency_table)
#         cramer_v = np.sqrt(chi2 / (col1.shape[0] * (min(contingency_table.shape) - 1)))
#         return cramer_v
#     elif col1.dtype != 'object' and col2.dtype != 'object':  # Числовые-Числовые
#         corr, _ = pearsonr(col1, col2)
#         return corr
#     else:  # Числовые-Категориальные
#         # Применяем тест хи-квадрат или ранговую корреляцию
#         if col1.dtype != 'object':  # Числовой столбец в первом месте
#             corr, _ = spearmanr(col1, col2)
#         else:  # Числовой столбец во втором месте
#             corr, _ = spearmanr(col2, col1)
#         return corr

# # Создаем пустую матрицу для хранения корреляций
# columns = list(df.columns)
# columns.remove('Start Date')
# columns.remove('End Date')
# columns.remove('Id')
# columns.remove('Duration')
# columns.remove('Datetime')
# columns.remove('Time of the year')
# correlation_matrix = pd.DataFrame(index=columns, columns=columns)

# # Заполняем матрицу корреляции
# for col1 in columns:
#     for col2 in columns:
#         correlation_matrix.loc[col1, col2] = calc_correlation(df[col1], df[col2])

# # Преобразуем все значения в числовой формат для дальнейшего отображения
# correlation_matrix = correlation_matrix.astype(float)

# # Строим тепловую карту для отображения матрицы корреляций
# plt.figure(figsize=(8, 6))
# sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
# plt.title('Матрица корреляций (числовые и категориальные данные)', fontsize=16)
# plt.show()

In [ ]:
merged_df.groupby(['Promo', 'Days'])['Promo'].agg(['sum', 'count'])

In [ ]:
merged_df = merged_df.drop(columns=['Time of the year'])

In [ ]:
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns

# plt.figure(figsize=(8, 6))
# sns.countplot(x='time_of_day', data=r, palette='Set2')

# plt.title('Распределение категориальных признаков', fontsize=16)
# plt.xlabel('Категория', fontsize=12)
# plt.ylabel('Частота', fontsize=12)

# plt.show()

In [9]:
m = r.copy()

In [11]:
merged_df = m.copy()

In [13]:
merged_df['Start District'] = merged_df['Start District'].apply(lambda x: x.lower().replace(' ', '-'))

In [15]:
set(merged_df['Start District'])

{'заречный',
 'ленинский',
 'октябрьский',
 'северо-западный',
 'центральный',
 'юго-восточный'}

In [17]:
merged_df['Start Location'] = merged_df['Start Location'].apply(lambda x: x.lower())
merged_df['End Location'] = merged_df['End Location'].apply(lambda x: x.lower())

In [19]:
set(merged_df['Start Location'])

{'береговая',
 'березовая',
 'буденного',
 'вишневая',
 'вокзальная',
 'восточная',
 'гагарина',
 'гоголя',
 'горького',
 'дачная',
 'дзержинского',
 'дорожная',
 'дружбы',
 'железнодорожная',
 'заводская',
 'западная',
 'заречная',
 'зеленая',
 'калинина',
 'карла маркса',
 'кирова',
 'колхозная',
 'комарова',
 'коммунальная',
 'комсомольская',
 'кооперативная',
 'космонавтов',
 'красная',
 'красноармейская',
 'крупской',
 'куйбышева',
 'ленина',
 'лермонтова',
 'лесная',
 'ломоносова',
 'луговая',
 'майская',
 'матросова',
 'маяковского',
 'мира',
 'мичурина',
 'молодежная',
 'московская',
 'набережная',
 'нагорная',
 'некрасова',
 'новая',
 'овражная',
 'озерная',
 'октябрьская',
 'парковая',
 'партизанская',
 'первомайская',
 'пионерская',
 'победы',
 'подгорная',
 'полевая',
 'почтовая',
 'пролетарская',
 'пушкина',
 'рабочая',
 'речная',
 'рябиновая',
 'садовая',
 'свердлова',
 'свободы',
 'северная',
 'сиреневая',
 'советская',
 'совхозная',
 'солнечная',
 'сосновая',
 'спортивная',
 'степная',
 'строителей',
 'строительная',
 'суворова',
 'труда',
 'трудовая',
 'ул береговая',
 'ул березовая',
 'ул буденного',
 'ул вишневая',
 'ул вокзальная',
 'ул восточная',
 'ул гагарина',
 'ул гоголя',
 'ул горького',
 'ул дачная',
 'ул дзержинского',
 'ул дорожная',
 'ул дружбы',
 'ул железнодорожная',
 'ул заводская',
 'ул западная',
 'ул заречная',
 'ул зеленая',
 'ул калинина',
 'ул карла маркса',
 'ул кирова',
 'ул колхозная',
 'ул комарова',
 'ул коммунальная',
 'ул комсомольская',
 'ул кооперативная',
 'ул космонавтов',
 'ул красная',
 'ул красноармейская',
 'ул крупской',
 'ул куйбышева',
 'ул ленина',
 'ул лермонтова',
 'ул лесная',
 'ул ломоносова',
 'ул луговая',
 'ул майская',
 'ул матросова',
 'ул маяковского',
 'ул мира',
 'ул мичурина',
 'ул молодежная',
 'ул московская',
 'ул набережная',
 'ул нагорная',
 'ул некрасова',
 'ул новая',
 'ул овражная',
 'ул озерная',
 'ул октябрьская',
 'ул парковая',
 'ул партизанская',
 'ул первомайская',
 'ул пионерская',
 'ул победы',
 'ул подгорная',
 'ул полевая',
 'ул почтовая',
 'ул пролетарская',
 'ул пушкина',
 'ул рабочая',
 'ул речная',
 'ул рябиновая',
 'ул садовая',
 'ул свердлова',
 'ул свободы',
 'ул северная',
 'ул сиреневая',
 'ул советская',
 'ул совхозная',
 'ул солнечная',
 'ул сосновая',
 'ул спортивная',
 'ул степная',
 'ул строителей',
 'ул строительная',
 'ул суворова',
 'ул труда',
 'ул трудовая',
 'ул цветочная',
 'ул центральная',
 'ул чапаева',
 'ул чехова',
 'ул чкалова',
 'ул шевченко',
 'ул школьная',
 'ул шоссейная',
 'ул энергетиков',
 'ул энтузиастов',
 'ул юбилейная',
 'ул южная',
 'ул. береговая',
 'ул. березовая',
 'ул. буденного',
 'ул. вишневая',
 'ул. вокзальная',
 'ул. восточная',
 'ул. гагарина',
 'ул. гоголя',
 'ул. горького',
 'ул. дачная',
 'ул. дзержинского',
 'ул. дорожная',
 'ул. дружбы',
 'ул. железнодорожная',
 'ул. заводская',
 'ул. западная',
 'ул. заречная',
 'ул. зеленая',
 'ул. калинина',
 'ул. карла маркса',
 'ул. кирова',
 'ул. колхозная',
 'ул. комарова',
 'ул. коммунальная',
 'ул. комсомольская',
 'ул. кооперативная',
 'ул. космонавтов',
 'ул. красная',
 'ул. красноармейская',
 'ул. крупской',
 'ул. куйбышева',
 'ул. ленина',
 'ул. лермонтова',
 'ул. лесная',
 'ул. ломоносова',
 'ул. луговая',
 'ул. майская',
 'ул. матросова',
 'ул. маяковского',
 'ул. мира',
 'ул. мичурина',
 'ул. молодежная',
 'ул. московская',
 'ул. набережная',
 'ул. нагорная',
 'ул. некрасова',
 'ул. новая',
 'ул. овражная',
 'ул. озерная',
 'ул. октябрьская',
 'ул. парковая',
 'ул. партизанская',
 'ул. первомайская',
 'ул. пионерская',
 'ул. победы',
 'ул. подгорная',
 'ул. полевая',
 'ул. почтовая',
 'ул. пролетарская',
 'ул. пушкина',
 'ул. рабочая',
 'ул. речная',
 'ул. рябиновая',
 'ул. садовая',
 'ул. свердлова',
 'ул. свободы',
 'ул. северная',
 'ул. сиреневая',
 'ул. советская',
 'ул. совхозная',
 'ул. солнечная',
 'ул. сосновая',
 'ул. спортивная',
 'ул. степная',
 'ул. строителей',
 'ул. строительная',
 'ул. суворова',
 'ул. труда',
 'ул. трудовая',
 'ул. цветочная',
 'ул. центральная',
 'ул. чапаева',
 'ул. чехова',
 'ул. чкалова',
 'ул. шевченко',
 'ул. школьная',
 'ул. шоссейная',
 'ул. энергетиков',
 'ул. энтузиастов',
 'ул. юбилейная',
 'ул. южная',
 'ул.береговая',
 'ул.березовая',
 'ул.буденного',
 'ул.вишневая',
 'ул.вокзальная',
 'ул.восточная',
 'ул.гагарина',
 'ул.гоголя',
 'ул.горького',
 'ул.дачная',
 'ул.дзержинского',
 'ул.дорожная',
 'ул.дружбы',
 'ул.железнодорожная',
 'ул.заводская',
 'ул.западная',
 'ул.заречная',
 'ул.зеленая',
 'ул.калинина',
 'ул.карла маркса',
 'ул.кирова',
 'ул.колхозная',
 'ул.комарова',
 'ул.коммунальная',
 'ул.комсомольская',
 'ул.кооперативная',
 'ул.космонавтов',
 'ул.красная',
 'ул.красноармейская',
 'ул.крупской',
 'ул.куйбышева',
 'ул.ленина',
 'ул.лермонтова',
 'ул.лесная',
 'ул.ломоносова',
 'ул.луговая',
 'ул.майская',
 'ул.матросова',
 'ул.маяковского',
 'ул.мира',
 'ул.мичурина',
 'ул.молодежная',
 'ул.московская',
 'ул.набережная',
 'ул.нагорная',
 'ул.некрасова',
 'ул.новая',
 'ул.овражная',
 'ул.озерная',
 'ул.октябрьская',
 'ул.парковая',
 'ул.партизанская',
 'ул.первомайская',
 'ул.пионерская',
 'ул.победы',
 'ул.подгорная',
 'ул.полевая',
 'ул.почтовая',
 'ул.пролетарская',
 'ул.пушкина',
 'ул.рабочая',
 'ул.речная',
 'ул.рябиновая',
 'ул.садовая',
 'ул.свердлова',
 'ул.свободы',
 'ул.северная',
 'ул.сиреневая',
 'ул.советская',
 'ул.совхозная',
 'ул.солнечная',
 'ул.сосновая',
 'ул.спортивная',
 'ул.степная',
 'ул.строителей',
 'ул.строительная',
 'ул.суворова',
 'ул.труда',
 'ул.трудовая',
 'ул.цветочная',
 'ул.центральная',
 'ул.чапаева',
 'ул.чехова',
 'ул.чкалова',
 'ул.шевченко',
 'ул.школьная',
 'ул.шоссейная',
 'ул.энергетиков',
 'ул.энтузиастов',
 'ул.юбилейная',
 'ул.южная',
 'цветочная',
 'центральная',
 'чапаева',
 'чехова',
 'чкалова',
 'шевченко',
 'школьная',
 'шоссейная',
 'энергетиков',
 'энтузиастов',
 'юбилейная',
 'южная'}

In [21]:
merged_df['Start Location'] = merged_df['Start Location'].apply(lambda x: x.lower().replace('ул.', '').replace('ул ', '').strip())
merged_df['End Location'] = merged_df['End Location'].apply(lambda x: x.lower().replace('ул.', '').replace('ул ', '').strip())

In [23]:
len(set(merged_df['Start Location']))

91

In [25]:
len(set(merged_df['End Location']))

91

In [29]:
grouped_streets_by_district = merged_df.groupby('Start District')['Start Location'].unique().to_frame()
grouped_streets_by_district = pd.DataFrame(grouped_streets_by_district)
grouped_streets_by_district['1'] = grouped_streets_by_district['Start Location'].apply(len)

In [31]:
grouped_streets_by_district.sort_values(by='1', ascending=False)

                                                    Start Location   1
Start District
центральный      [труда, пролетарская, зеленая, энтузиастов, пу...  30
юго-восточный    [шевченко, лесная, коммунальная, центральная, ...  22
ленинский        [комарова, западная, свободы, подгорная, лермо...  14
северо-западный  [первомайская, новая, школьная, рябиновая, раб...  13
заречный         [чехова, шоссейная, комсомольская, пионерская,...   6
октябрьский      [буденного, восточная, майская, ломоносова, сп...   6

In [33]:
missing_districts = merged_df[merged_df['Start Location'].isna()]
print(f"Пропусков в Start District: {len(missing_districts)}")
print(missing_districts[['Start Location', 'End Location', 'Start District']].head(10))

Пропусков в Start District: 0
Empty DataFrame
Columns: [Start Location, End Location, Start District]
Index: []

In [ ]:
# reversed_dict = {}
# for k, v in grouped_streets_by_district.drop(columns=['1']).to_dict()['Start Location'].items():
#     for v1 in v:
#         reversed_dict[v1] = k

In [ ]:
# merged_df.groupby('Start District')['Start Location'].value_counts()

In [ ]:
pd.set_option("display.max_rows", 50)

In [ ]:
# start_dist = pd.DataFrame(merged_df[['Start District', 'Start Location']].value_counts()).sort_values(by='count', ascending=False)

In [ ]:
# merged_df.groupby('End Location')['End Location'].agg('count').sort_values()[:50]

In [ ]:
merged_df['End District'] = merged_df['End District'].apply(lambda x: x.lower().replace(' ', '-'))

In [ ]:
merged_df['End Location'] = merged_df['End Location'].apply(lambda x: x.lower().replace('ул.', '').replace('.', '').strip())
merged_df['End Location'] = merged_df['End Location'].apply(lambda x: x.lower().replace('ул ', '').replace('.', '').strip())

In [ ]:
len(set(merged_df['End Location']))

In [ ]:
# a = merged_df[['Start Location', 'End Location', 'Distance']].copy()
# dist = {}

In [ ]:
# a['Start Location'] = a['Start Location'].apply(lambda i: reversed_dict[i])
# a['End Location'] = a['End Location'].apply(lambda i: reversed_dict[i])

In [ ]:
# a

In [ ]:
# for _, i in a.iterrows():
#     if i[0] == i[1]:
#         continue
#     if i[0] + ',' + i[1] in dist.keys():
#         dist[i[0] + ',' + i[1]] = (dist[i[0] + ',' + i[1]] + i[2]) / 2
#     elif i[1] + ',' + i[0] in dist.keys():
#         dist[i[1] + ',' + i[0]] = (dist[i[1] + ',' + i[0]] + i[2]) / 2
#     else:
#         dist[i[0] + ',' + i[1]] = i[2]

In [ ]:
# dist

In [ ]:
# g = pd.DataFrame(dist.items())
# g['start'] = g[0].apply(lambda x: x.split(',')[0])

In [ ]:
# g['end'] = g[0].apply(lambda x: x.split(',')[1])

In [ ]:
# g = g.drop(columns=[0])

In [ ]:
# g

In [ ]:
# import matplotlib.pyplot as plt
# import seaborn as sns

# # Создадим график для Start Location, End Location и Distance
# plt.figure(figsize=(12, 8))

# # Создадим scatter plot
# sns.scatterplot(data=g, x='start', y='end', size=1, hue=1, palette='viridis', sizes=(20, 200))

# # Настроим внешний вид графика
# plt.title('Start Location vs End Location with Distance', fontsize=16)
# plt.xlabel('Start Location', fontsize=12)
# plt.ylabel('End Location', fontsize=12)
# plt.xticks(rotation=90)  # Повернем метки по оси X
# plt.legend(title='Distance', bbox_to_anchor=(1.05, 1), loc='upper left')  # Легенда с размерами

# # Показать график
# plt.tight_layout()
# plt.show()

In [ ]:
# grouped_streets_by_district = merged_df.groupby('Start District')['Start Location'].unique().to_frame()
# grouped_streets_by_district = pd.DataFrame(grouped_streets_by_district)
# grouped_streets_by_district['1'] = grouped_streets_by_district['Start Location'].apply(len)

In [ ]:
# import pandas as pd
# import networkx as nx
# import matplotlib.pyplot as plt

# G = nx.Graph()

# # Добавляем ребра с весами
# for _, row in g.iterrows():
#     start = row['start']
#     end = row['end']
#     distance = row[1]
#     G.add_edge(start, end, weight=distance)

# # Визуализация: отрисуем упрощённый граф с весами
# plt.figure(figsize=(16, 12))

# # Используем kamada_kawai_layout для более аккуратного расположения вершин
# pos = nx.kamada_kawai_layout(G)

# edges = G.edges(data=True)
# weights = [data['weight'] / 1000 for _, _, data in edges]  # нормализуем веса для толщины линий

# # Рисуем вершины и рёбра
# nx.draw(G, pos, node_color='skyblue', edge_color=weights, with_labels=True, width=weights, font_size=20)

# plt.title("Взвешенный граф перемещений по улицам", fontsize=16)
# plt.axis('off')
# plt.tight_layout()
# plt.show()

In [ ]:
merged_df['weekday'] = merged_df['Start Date'].dt.weekday
merged_df['Start Month'] = merged_df['Start Date'].apply(lambda x: x.month)
merged_df['End Month'] = merged_df['End Date'].dt.month
seasons = {
    12: 'Зима', 1: 'Зима', 2: 'Зима',
    3: 'Весна', 4: 'Весна', 5: 'Весна',
    6: 'Лето', 7: 'Лето', 8: 'Лето',
    9: 'Осень', 10: 'Осень', 11: 'Осень'
}
merged_df['Start Season'] = merged_df['Start Month'].map(seasons)
merged_df['End Season'] = merged_df['End Month'].map(seasons)
merged_df['Time start'] = merged_df['Start Date'].dt.time
merged_df['Time end'] = merged_df['End Date'].dt.time
merged_df['Trip Duration'] = (merged_df['End Date'] - merged_df['Start Date']).dt.total_seconds() / 60
def get_rate(weekday, hour):
    if weekday < 5:  # Пн–Пт
        if 1 <= hour < 6:
            return 3
        elif 6 <= hour < 10:
            return 4
        elif 10 <= hour < 16:
            return 5
        elif 16 <= hour < 22:
            return 6
        else:  # 22:00 – 01:00 (hour 22, 23, 0)
            return 5
    else:  # Сб–Вс
        if 1 <= hour < 6:
            return 3
        elif 6 <= hour < 10:
            return 4
        elif 10 <= hour < 16:
            return 6
        elif 16 <= hour < 22:
            return 7
        else:  # 22:00 – 01:00 (hour 22, 23, 0)
            return 6

merged_df['Start Hour'] = merged_df['Start Date'].dt.hour
merged_df['Rate per Minute'] = merged_df.apply(lambda row: get_rate(row['weekday'], row['Start Hour']), axis=1)
merged_df['Trip Cost'] = merged_df['Trip Duration'] * merged_df['Rate per Minute']

In [ ]:
m = merged_df.copy()

In [ ]:
merged_df['DateOnly'] = merged_df['Datetime'].dt.date

# Теперь можно сгруппировать по дате
gbd = merged_df.groupby('DateOnly')

list_data = []
for date, group in gbd:
    list_data.append([date, group])

In [ ]:
list_data

In [ ]:
average_samokat = []
for i in list_data:
    da = [i[0]]
    datafr = i[1]
    first = datafr['Start Location'].value_counts().to_frame()
    second = datafr['End Location'].value_counts().to_frame()
    second.columns = ['leave']
    first.columns = ['inter']
    second.index.name = 'Start Location'
    fin = first.merge(second, on='Start Location')
    fin['turn_per_day'] = fin['inter'] + fin['leave']
    da.append(fin.sort_values(by='turn_per_day', ascending=False))
    average_samokat.append(da)

def union_all_data(x):
    h = x[0]
    for k in range(len(x)):
        h = pd.concat([h, x[k]])
    return h

all_trafic = union_all_data(list(map(lambda x: x[1], average_samokat)))
all_trafic = all_trafic.groupby('Start Location')[['inter', 'leave', 'turn_per_day']].agg('sum').sort_values(by='turn_per_day', ascending=False)

In [ ]:
sum(all_trafic['turn_per_day'])

In [ ]:
len(merged_df)

In [ ]:
list_data[0][1]['weekday']

In [ ]:
from tqdm import tqdm

weekdays = {}

# tqdm добавляет прогресс-бар к итерации
for i in tqdm(list_data, desc="Обработка данных по дням недели"):
    f = dict(tuple(i[1].groupby('weekday')))
    ind = list(set(f.keys()))
    for k in ind:
        if isinstance(weekdays.get(k, 0), int):
            weekdays[k] = f[k]
        else:
            weekdays[k] = pd.concat([weekdays[k], f[k]])

In [ ]:
weekdays

In [ ]:
average_samokat_to_weekdays = []
for i in weekdays.keys():
    da = [i]
    datafr = weekdays[i]
    first = datafr['Start Location'].value_counts().to_frame()
    second = datafr['End Location'].value_counts().to_frame()
    second.columns = ['leave']
    first.columns = ['inter']
    second.index.name = 'Start Location'
    fin = first.merge(second, on='Start Location')
    fin['turn_per_day'] = fin['inter'] + fin['leave']
    da.append(fin.sort_values(by='turn_per_day', ascending=False))
    average_samokat_to_weekdays.append(da)

In [ ]:
average_samokat_to_weekdays

### Нулевая: Стоит ли закрывать некоторые точки? 
### Альтернативная: Не стоит закрывать никакие точки.

Будем считать, что обыточные места - это те места, которые приносят меньше 10000 рублей в 2 месяца

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Пусть data — это твой список из [день, DataFrame]
# Метрики
metrics = ['inter', 'leave', 'turn_per_day']

# Для каждой метрики
for metric in metrics:
    # Для каждого дня недели
    for weekday, df in average_samokat_to_weekdays:
        plt.figure(figsize=(16, 6))
        
        # Берем значения по метрике и улицам
        values = df[metric]
        streets = df.index.tolist()
        
        # Строим гистограмму
        sns.barplot(x=streets, y=values, palette='viridis')

        plt.title(f'{metric.capitalize()} — День недели {weekday}')
        plt.xlabel('Улица')
        plt.ylabel(metric)
        plt.xticks(rotation=90)  # Повернуть подписи улиц
        plt.grid(axis='y')
        plt.tight_layout()
        plt.show()

Вывод: не стоит закрывать ни одной точки, потому что по убы

In [ ]:
# reversed_dict = {}
# for k, v in grouped_streets_by_district.drop(columns=['1']).to_dict()['Start Location'].items():
#     for v1 in v:
#         reversed_dict[v1] = k

# all_trafic['district'] = all_trafic.index
# all_trafic['district'] = all_trafic['district'].apply(lambda x: reversed_dict[x])

In [ ]:
# reversed_dict

In [ ]:
# all_trafic

In [ ]:
# all_trafic = all_trafic.groupby('district')[['inter', 'leave', 'turn_per_day']].agg('sum').sort_values(by='turn_per_day', ascending=False)

In [ ]:
# merged_df.groupby('Start District')['Promo'].agg('sum').to_frame().sort_values(by='Promo', ascending=False)

In [ ]:
# testing = merged_df.copy()

In [ ]:
# testing = testing[testing['Start District'] == testing['End District']].groupby('Start District')['End District'].agg('count').to_frame().sort_values(by='End District', ascending=False)

In [ ]:
# all_trafic

In [ ]:
# testing['district'] = testing.index
# all_trafic['district'] = all_trafic.index

In [ ]:
# testing.sort_values(by='End District', ascending=False)

In [ ]:
# testing = testing.reset_index()
# all_trafic = all_trafic.reset_index()

# # Теперь можно выполнить merge
# t = testing.merge(all_trafic, on='district')

In [ ]:
# all_trafic.index.name = 'Start District'

In [ ]:
# t.drop(columns=['index', 'Start District_x', 'Start District_y'])

In [ ]:
# merged_df.columns

In [ ]:
# merged_df.columns

In [ ]:
# all_trafic

In [ ]:
(
    weekdays[0]
    .groupby('Promo')
    .apply(lambda x: x)
    .loc[1]
    .groupby('Start Location')['Start Location']
    .agg('count')
    .sort_values(ascending=False)  # <-- сортировка по убыванию
    .to_frame(name='count')        # <-- имя колонки для наглядности
)